#!/usr/bin/env python3
"""Fail closed on likely private data or unreviewed binaries in a skill folder."""

import argparse
import re
import sys
from pathlib import Path


WINDOWS_USER_ROOT = r"[A-Z]:\\" + "Users" + r"\\"
MAC_USER_ROOT = "/" + "Users" + "/"
LINUX_USER_ROOT = "/" + "home" + "/"

PATTERNS = [
    ("email address", re.compile(r"(?i)\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b")),
    ("Chinese mobile number", re.compile(r"(?<!\d)1[3-9]\d{9}(?!\d)")),
    ("international phone number", re.compile(r"(?<!\w)\+\d[\d -]{7,}\d(?!\w)")),
    ("Chinese identity-card number", re.compile(r"(?<!\d)\d{17}[\dXx](?!\d)")),
    (
        "local user path",
        re.compile(
            rf"(?i)(?:{WINDOWS_USER_ROOT}|{MAC_USER_ROOT}|{LINUX_USER_ROOT})[^\\/\s]+"
        ),
    ),
    ("GitHub token", re.compile(r"\bgh(?:p|o|u|s|r)_[A-Za-z0-9]{20,}\b")),
    ("generic API secret", re.compile(r"(?i)\b(?:api[_-]?key|secret[_-]?key)\s*[:=]\s*['\"][^'\"]{8,}")),
    ("private key", re.compile("-----BEGIN " + r"(?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
]
FORBIDDEN_SUFFIXES = {".pyc", ".pyo", ".p12", ".pfx", ".key", ".pem"}
REVIEW_SUFFIXES = {
    ".7z", ".doc", ".docx", ".gif", ".gz", ".jpeg", ".jpg", ".pdf",
    ".png", ".ppt", ".pptx", ".rar", ".tar", ".tif", ".tiff", ".xls",
    ".xlsx", ".zip",
}
SKIP_DIRS = {".git", ".hg", ".svn"}


def line_number(text, index):
    return text.count("\n", 0, index) + 1


def iter_files(root):
    for path in root.rglob("*"):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.is_file() or path.is_symlink():
            yield path


def audit(root, deny_terms):
    findings = []
    for path in iter_files(root):
        relative = path.relative_to(root)
        relative_text = relative.as_posix()

        if path.is_symlink():
            findings.append((relative_text, None, "symbolic link requires manual review"))
            continue
        if path.suffix.casefold() in FORBIDDEN_SUFFIXES:
            findings.append((relative_text, None, "forbidden sensitive/generated file type"))
            continue
        if path.suffix.casefold() in REVIEW_SUFFIXES:
            findings.append((relative_text, None, "binary/archive requires manual privacy review"))
            continue

        for index, term in enumerate(deny_terms, start=1):
            if term.casefold() in relative_text.casefold():
                findings.append((relative_text, None, f"deny term #{index} appears in path"))

        try:
            raw = path.read_bytes()
            if b"\x00" in raw:
                findings.append((relative_text, None, "binary content requires manual privacy review"))
                continue
            text = raw.decode("utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            findings.append((relative_text, None, f"could not audit as UTF-8 text: {exc}"))
            continue

        for label, pattern in PATTERNS:
            for match in pattern.finditer(text):
                findings.append((relative_text, line_number(text, match.start()), label))
        for index, term in enumerate(deny_terms, start=1):
            start = 0
            folded_text = text.casefold()
            folded_term = term.casefold()
            while True:
                position = folded_text.find(folded_term, start)
                if position < 0:
                    break
                findings.append(
                    (relative_text, line_number(text, position), f"deny term #{index}")
                )
                start = position + len(folded_term)
    return findings


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Scan a skill folder for common personal data, secrets, generated bytecode, "
            "and binaries that require manual review. Matches are never printed."
        )
    )
    parser.add_argument(
        "root",
        nargs="?",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    parser.add_argument(
        "--deny-term",
        action="append",
        default=[],
        help="Known private term to detect without echoing it in output; repeat as needed",
    )
    args = parser.parse_args()
    root = args.root.resolve()
    if not root.is_dir():
        print("ERROR: audit root must be an existing directory")
        return 2
    if any(not term for term in args.deny_term):
        print("ERROR: --deny-term cannot be empty")
        return 2

    findings = audit(root, args.deny_term)
    if findings:
        for path, line, label in findings:
            location = f"{path}:{line}" if line is not None else path
            print(f"FINDING: {location}: {label}")
        print(f"Privacy audit failed with {len(findings)} finding(s).")
        return 1
    print(f"Privacy audit passed: {root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
